## Tensor

- Tensor는 Pytorch의 자료형
- Tensor는 단일 데이터 타입으로 이루어진 자료들의 다차원 행렬
- Tensor는 간단한 명령어로 GPU 연산을 할 수 있다. .cuda()를 추가해 주면 된다.

### Tensor의 선언

In [7]:
import torch
import numpy as np

In [3]:
x = torch.Tensor(3) #초기화 되지 않은 Tensor를 생성한다.
x

#GPU tensor는 torch.cuda.Tensor(3) 식으로 선언해 주면 된다.

tensor([                    0., -36893488147419103232.,      -132215568596992.])

In [4]:
y = torch.Tensor(3, 3) #초기화 되지 않은 Tensor를 생성한다.
y

#GPU tensor는 torch.cuda.Tensor(3, 3) 식으로 선언해 주면 된다.

tensor([[                    0.0000, -36893488147419103232.0000,
                             0.0000],
        [-36893488147419103232.0000,                     0.0000,
                             0.0000],
        [                    0.0000,                     0.0000,
                             0.0000]])

### Tensor의 random 선언

In [5]:
a = torch.rand(3, 3) #rand는 0 ~ 1 사이의 uniform distribution random
a

tensor([[0.3089, 0.5450, 0.2704],
        [0.0963, 0.5829, 0.0850],
        [0.0261, 0.0640, 0.2017]])

In [6]:
b = torch.randn(3, 3) #randn는 0 ~ 1 사이의 normal distribution random
b

tensor([[ 0.0702,  0.1806, -1.0908],
        [-0.1752,  0.4939, -1.8782],
        [-1.3384,  0.0159, -0.2766]])

### Numpy에서 Tensor로

In [8]:
a = np.array([1, 2, 3, 4])
b = torch.Tensor(a) #단순히 Tensor에 넣어주면 변환된다.
b

tensor([1., 2., 3., 4.])

### Tensor에서  Numpy로

In [9]:
a = torch.rand(3, 3)
b = a.numpy() #단순히 Tensor 변수에서 numpy() 메서드를 호출하면 변환된다.
b

array([[0.05079883, 0.96433324, 0.6975273 ],
       [0.669832  , 0.25096315, 0.97871727],
       [0.7586607 , 0.6685751 , 0.01797998]], dtype=float32)

### Tensor의 형태 변환(view)

In [11]:
a = torch.rand(3, 3)
print(a)
a = a.view(1, 1, 3, 3) #view에 변환할 형태를 넣어주면 돈다. 4차원 행렬이 된다.
print(a)

tensor([[0.7540, 0.6585, 0.5049],
        [0.7242, 0.7522, 0.3540],
        [0.9209, 0.4321, 0.5459]])
tensor([[[[0.7540, 0.6585, 0.5049],
          [0.7242, 0.7522, 0.3540],
          [0.9209, 0.4321, 0.5459]]]])


### Tensor 합치기

In [12]:
a = torch.randn(1, 1, 3, 3)
b = torch.randn(1, 1, 3, 3)
c = torch.cat((a, b), 0) #0은 차원. 각 해당 tensor를 dim에 맞춰 합쳐 준다.
c

tensor([[[[ 0.2994, -1.2702,  0.2555],
          [ 0.3550, -1.1052,  0.8943],
          [-0.1318, -0.6716, -0.2217]]],


        [[[ 1.3070,  0.3053,  2.6665],
          [ 3.4230, -1.4231,  0.3703],
          [ 1.6967, -0.1317, -0.0381]]]])

In [13]:
a + b
#cf. + 연산자를 사용하면 단순히 값을 합친다.

tensor([[[[ 1.6064, -0.9650,  2.9220],
          [ 3.7780, -2.5283,  1.2646],
          [ 1.5649, -0.8033, -0.2598]]]])

### Tensor 계산을 GPU로

In [14]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

if torch.cuda.is_available(): #GPU 사용 가능하면
    x = x.cuda() #.cuda()만 추가해 주면 된다.
    y = y.cuda()

### 그 외

In [15]:
a = torch.rand(3, 3)
a.mean() #평균

tensor(0.4594)

In [16]:
a.sum() #합

tensor(4.1344)