torch.nn 과 torch.nn.functional 에서 지원하는 함수들은 거의 유사한데, 사용하는 방식에서 약간의 차이가 있다.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## nn.functional.Conv2d

In [2]:
input = torch.ones(1, 1, 3, 3, requires_grad=True)
filter = torch.ones(1, 1, 3, 3)

input

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [3]:
out = F.conv2d(input, filter) #torch.nn.functional의 conv2d는 weight(filter)를 직접 넣어줘야 한다.
out

tensor([[[[9.]]]], grad_fn=<ThnnConv2DBackward>)

In [4]:
out.backward()
print(out.grad_fn)
print(input.grad)

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


In [5]:
input = torch.ones(1, 1, 3, 3, requires_grad=True)
filter = filter + 1

out = F.conv2d(input, filter)
print(out)

out.backward()
print(out.grad_fn)
print(input.grad)

tensor([[[[18.]]]], grad_fn=<ThnnConv2DBackward>)
tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]]]])


## nn.Conv2d

In [6]:
input = torch.ones(1, 1, 3, 3, requires_grad=True)

In [7]:
func = nn.Conv2d(1, 1, 3) #nn의 Conv2d는 input_dim, output_dim, kernel_size
func.weight #여기서는 랜덤 값

#다른 모델에서 가져온 값을 넣을 때에는 
#func.weight = torch.nn.Parameter(torch.Tensor([.....])) 식으로 원하는 값을 넣어줄 수 있다.

Parameter containing:
tensor([[[[-0.1283, -0.0544,  0.2393],
          [-0.1364,  0.0057, -0.2502],
          [-0.1555, -0.0090, -0.2002]]]], requires_grad=True)

In [8]:
out = func(input)
print(out)

tensor([[[[-0.4714]]]], grad_fn=<ThnnConv2DBackward>)


In [10]:
print(input.grad)

None


In [11]:
out.backward()

In [12]:
print(input.grad)

tensor([[[[-0.1283, -0.0544,  0.2393],
          [-0.1364,  0.0057, -0.2502],
          [-0.1555, -0.0090, -0.2002]]]])


## Define the Network

- class 선언으로 사용하고자 하는 Network를 직접 구현할 수 있다.
- class로 선언할 Network에 필수 요소는
    - def \__init__(self):
    - def forward(self, x):