## 1. Import Required Libraries

In [1]:
import torch
import torch.nn as nn
import torch.nn.init as init
from torch.autograd import Variable

## 2. Input Data

In [2]:
img = Variable(torch.ones(1,1,3,3)) #3 x 3 tensor 생성
print(img) #1x1x3x3

tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])


## 3. Set All Weights to One

In [3]:
#이미지에 대해서는 Convolutional layer가 성능이 좋기 때문에 이를 적용한 Autoencoder를 만들 수 있다.
#encoding 시에는 CNN과 같이 Convolution layer를 써주고, decoding에는 Conv의 역 연산을 하는 Convolution Transposed layer을 써준다.

transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=1, padding=0, output_padding=0, bias=False)
# (in_channels, out_channels, kernel_size, stride=1, padding=0, output_padding=0, groups=1, bias=True, dilation=1)

#3x3 필터로 ConvT를 적용한다.
print(transpose.weight.data)

init.constant_(transpose.weight.data,1)

tensor([[[[ 0.3128, -0.3078,  0.0146],
          [-0.1770,  0.2352, -0.2788],
          [-0.1566,  0.0028,  0.3162]]]])


tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]])

## Kernel Size=3, stride=1, padding=0, output_padding=0

In [4]:
transpose(img) #결과는 이와 같이 나온다. #1x1x5x5
#3 x 3 필터가 stride 1로 움직이므로, 큰 숫자가 찍힌 곳이 많은 영향을 끼친 요소이다.
#ex. 가운데 9는 3x3 필터가 총 9번 지나가고, 좌측 최상단의 1 영역은 3x3 필터가 딱 한번 지나간다.

tensor([[[[1., 2., 3., 2., 1.],
          [2., 4., 6., 4., 2.],
          [3., 6., 9., 6., 3.],
          [2., 4., 6., 4., 2.],
          [1., 2., 3., 2., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

## Kernel Size=3, stride=2, padding=0, output_padding=0

In [5]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, output_padding=0, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img) #1x1x7x7

tensor([[[[1., 1., 2., 1., 2., 1., 1.],
          [1., 1., 2., 1., 2., 1., 1.],
          [2., 2., 4., 2., 4., 2., 2.],
          [1., 1., 2., 1., 2., 1., 1.],
          [2., 2., 4., 2., 4., 2., 2.],
          [1., 1., 2., 1., 2., 1., 1.],
          [1., 1., 2., 1., 2., 1., 1.]]]],
       grad_fn=<ThnnConvTranspose2DBackward>)

## Kernel Size=3, stride=2, padding=1, output_padding=0

In [6]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=0, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img) #1x1x5x5
#ConvT에서의 padding의 Conv에서와 달리, 사이즈 만큼 이미지를 잘라낸다고 생각하면 된다.
#바로 위의 Kernel Size=3, stride=2, padding=0, output_padding=0의 결과와 달리 1만큼 잘렸다.

tensor([[[[1., 2., 1., 2., 1.],
          [2., 4., 2., 4., 2.],
          [1., 2., 1., 2., 1.],
          [2., 4., 2., 4., 2.],
          [1., 2., 1., 2., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)

## Kernel Size=3, stride=2, padding=0, output_padding=1

In [7]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=0, output_padding=1, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img) #1x1x8x8
#Conv의 padding과 같은 역할을 하는 것은 ouput_padding이다.
#바로 위의 Kernel Size=3, stride=2, padding=1, output_padding=0의 결과와 달리 1만큼 0이 추가 되었다.

tensor([[[[1., 1., 2., 1., 2., 1., 1., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [2., 2., 4., 2., 4., 2., 2., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [2., 2., 4., 2., 4., 2., 2., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [1., 1., 2., 1., 2., 1., 1., 0.],
          [0., 0., 0., 0., 0., 0., 0., 0.]]]],
       grad_fn=<ThnnConvTranspose2DBackward>)

## Kernel Size=3, stride=2, padding=1, output_padding=1

In [8]:
transpose = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=3, stride=2, padding=1, output_padding=1, bias=False)
init.constant_(transpose.weight.data,1)
transpose(img) #1x1x6x6
#원본의 2배로 늘어난다. 이렇게 2배로 늘려주는 ConvT를 자주 사용한다.

tensor([[[[1., 2., 1., 2., 1., 1.],
          [2., 4., 2., 4., 2., 2.],
          [1., 2., 1., 2., 1., 1.],
          [2., 4., 2., 4., 2., 2.],
          [1., 2., 1., 2., 1., 1.],
          [1., 2., 1., 2., 1., 1.]]]], grad_fn=<ThnnConvTranspose2DBackward>)